title: "Sindhuja Chaduvula"
description: "AI/ML Engineer | Responsible AI | Generative AI"
remote_theme: "pages-themes/minimal@v0.2.0"  # <- replace this line for other themes
plugins:
  - jekyll-remote-theme
